---
website_title:   'Proxy Pattern'
website_tagline: 'Ein Einblick in die Welt des Proxies in PHP'
your_github_username: it4need
your_github_reponame: php-proxy-pattern
title: 'Proxy Entwurfsmuster - Einführung in PHP'
lang:   de
date:   30.12.2018
author:
  - Jan André Schlösser
description: 'Proxy ist ein GoF-Strukturmuster und stellt ein Stellvertreter-Objekt oder Platzhalter (Proxy) für ein anderes Objekt zur Verfügung. Es bietet dadurch Kontrolle über die Objekterzeugung und dessen Zugriff.'
header-includes: |
include-before: |
include-after: |
...
